points_to_win:
  type: int
  default: 5
  min: 1
swap_immunity_seconds:
  type: int
  default: 0
  min: 0
round_time_minutes:
  type: int
  default: 5
  min: 1
unique_deaths:
  type: boolean
  default: true
hunger:
  type: boolean
  default: false
grace_period_minutes:
  type: int
  min: 0
  default: 0