points_to_win:
  type: int
  default: 5
  min: 1
swap_immunity_seconds:
  type: double
  default: 0
  min: 0
round_time_minutes:
  type: double
  default: 5
  min: 0.1
unique_deaths:
  type: boolean
  default: true
hunger:
  type: boolean
  default: false
grace_period_minutes:
  type: double
  min: 0
  default: 0
swap_points_period_minutes:
  type: double
  min: 0
  default: 0